
/**
 * ***************** DO NOT EDIT THIS FILE *****************
 *
 * TEST RUNNING FILE FOR CONFIGURATION OF THE NIGHTWATCH TESTS FOR THE PROJECT
 *
 * ***************** DO NOT EDIT THIS FILE *****************
 */

var log4js = require('log4js');
// https://github.com/nomiddlename/log4js-node/wiki/Layouts
var logFormat = {
	type: 'messagePassThrough'
}

// https://gist.github.com/branneman/8048520
global.rootRequire = function(name) {
    return require(__dirname + '/custom_modules/' + name);
}

var fileUtils = rootRequire("FSUtils");

fileUtils.cleanUp(function() {
	require('nightwatch/bin/runner.js');

	log4js.configure({
	  appenders: [
	    {
	    	type: 'console',
	    	layout: logFormat
	    },
		{
			type: "dateFile",
			filename: "target/log/nightwatch-raw",
			pattern: "-yyyy-MM-dd.log",
			alwaysIncludePattern: true,
			layout: logFormat,
			category: ['nightwatch', 'console']
		}
	  ],
	  replaceConsole: true
	});

});
